import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import styles from '../styles/Home.module.css';

export default function Home() {
  function handleSubmit(e) {
    e.preventDefault();
    axios.postForm('/api/image', new FormData(e.target)).then(console.log);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <form onSubmit={handleSubmit}>
        <input type='file' name='test' />
        <input type='text' name='test2' />
        <button type='submit'>Submit</button>
      </form>
    </div>
  );
}
